# Pydantic models FastAPI Glossary

In [14]:
import pandas as pd

# EDA
#load json file into DF:
df = pd.read_json("../../data/fastapi_glossary.json")
df.head()

   id              word                                            meaning
0   1    path parameter  Request parameters embedded in the URL path to...
1   2  endpoint (route)  A URL path in the API that accepts HTTP reques...
2   3   query parameter  Additional key–value pairs after ? in the URL,...
3   4      request body  Data sent with POST/PUT/PATCH requests, usuall...
4   5           uvicorn  ASGI web server used to run FastAPI apps. Comm...

In [9]:
df.describe().T

    count  mean     std  min   25%  50%    75%   max
id   14.0   7.5  4.1833  1.0  4.25  7.5  10.75  14.0

In [16]:
df["word"].value_counts()

word
path parameter                1
endpoint (route)              1
query parameter               1
request body                  1
uvicorn                       1
%20                           1
Field (pydantic)              1
DTO                           1
client                        1
schema                        1
Depends()                     1
payload                       1
field_validator (pydantic)    1
model_validator               1
Name: count, dtype: int64

In [17]:
len(df["word"])

14

### deserialize json object into pydantic model

In [21]:
df["word"]

0                 path parameter
1               endpoint (route)
2                query parameter
3                   request body
4                        uvicorn
5                            %20
6               Field (pydantic)
7                            DTO
8                         client
9                         schema
10                     Depends()
11                       payload
12    field_validator (pydantic)
13               model_validator
Name: word, dtype: object

In [28]:
df.keys().drop("id")

Index(['word', 'meaning'], dtype='object')

In [30]:
df

,id,word,meaning
0,1,path parameter,Request parameters embedded in the URL path to...
1,2,endpoint (route),A URL path in the API that accepts HTTP reques...
2,3,query parameter,"Additional key–value pairs after ? in the URL,..."
3,4,request body,"Data sent with POST/PUT/PATCH requests, usuall..."
4,5,uvicorn,ASGI web server used to run FastAPI apps. Comm...
5,6,%20,URL-encoded space character used in URL paths ...
6,7,Field (pydantic),Function to add metadata and validation constr...
7,8,DTO,Data Transfer Object—an object that carries da...
8,9,client,Program or device that makes requests to a ser...
9,10,schema,Structured blueprint defining data organizatio...
10,11,Depends(),FastAPI dependency injection tool to provide r...
11,12,payload,The actual data carried in an API request or r...
12,13,field_validator (pydantic),Custom function for per-field validation beyon...
13,14,model_validator,"Validator that runs on the entire model, with ..."

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       14 non-null     int64
 1   word     14 non-null     object
 2   meaning  14 non-null     object
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes

In [35]:
from pydantic import BaseModel

class FastAPI_Glossary(BaseModel):
    id: int
    word: str
    meaning: str

with open("../../data/fastapi_glossary.json") as f:
    data = json.load(f)

glossary = FastAPI_Glossary.model_validate(df)
glossary

ValidationError: 3 validation errors for FastAPI_Glossary
id
  Input should be a valid integer [type=int_type, input_value=<class 'int'>, input_type=type]
    For further information visit https://errors.pydantic.dev/2.11/v/int_type
word
  Input should be a valid string [type=string_type, input_value=<class 'str'>, input_type=type]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
meaning
  Input should be a valid string [type=string_type, input_value=<class 'str'>, input_type=type]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type