## Exercise 2.0 - Iris flower dataset (*)

In [1]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

### a, Check keys on iris loaded data to explore

In [9]:
iris = load_iris(as_frame=True)

In [10]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
iris.data.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [25]:
iris.data.shape

(150, 4)

In [26]:
iris.target.shape

(150,)

In [12]:
iris.target.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [13]:
iris.frame.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [16]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [24]:
import textwrap
print(textwrap.fill(iris.DESCR, width=90))

.. _iris_dataset:  Iris plants dataset --------------------  **Data Set Characteristics:**
:Number of Instances: 150 (50 in each of three classes) :Number of Attributes: 4 numeric,
predictive attributes and the class :Attribute Information:     - sepal length in cm     -
sepal width in cm     - petal length in cm     - petal width in cm     - class:
- Iris-Setosa             - Iris-Versicolour             - Iris-Virginica  :Summary
Statistics:  ============== ==== ==== ======= ===== ====================
Min  Max   Mean    SD   Class Correlation ============== ==== ==== ======= =====
==================== sepal length:   4.3  7.9   5.84   0.83    0.7826 sepal width:    2.0
4.4   3.05   0.43   -0.4194 petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!) ============== ==== ==== =======
===== ====================  :Missing Attribute Values: None :Class Distribution: 33.3% for
each of 3 classes. :Creator: R.A. Fisher :Donor: Michael Marshall
(MARSHALL%PLU@io.arc.nasa.gov) :Date: July, 1988  The famous Iris database, first used by
Sir R.A. Fisher. The dataset is taken from Fisher's paper. Note that it's the same as in
R, but not as in the UCI Machine Learning Repository, which has two wrong data points.
This is perhaps the best known database to be found in the pattern recognition literature.
Fisher's paper is a classic in the field and is referenced frequently to this day.  (See
Duda & Hart, for example.)  The data set contains 3 classes of 50 instances each, where
each class refers to a type of iris plant.  One class is linearly separable from the other
2; the latter are NOT linearly separable from each other.  .. dropdown:: References    -
Fisher, R.A. "The use of multiple measurements in taxonomic problems"     Annual Eugenics,
7, Part II, 179-188 (1936); also in "Contributions to     Mathematical Statistics" (John
Wiley, NY, 1950).   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene
Analysis.     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.   -
Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System     Structure and
Classification Rule for Recognition in Partially Exposed     Environments".  IEEE
Transactions on Pattern Analysis and Machine     Intelligence, Vol. PAMI-2, No. 1, 67-71.
- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions     on
Information Theory, May 1972, 431-433.   - See also: 1988 MLC Proceedings, 54-64.
Cheeseman et al"s AUTOCLASS II     conceptual clustering system finds 3 classes in the
data.   - Many, many more ...

In [21]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [22]:
iris.filename

'iris.csv'

In [23]:
iris.data_module

'sklearn.datasets.data'