## LanceDB  - a vector database for LLM applications

In [1]:
import lancedb

db = lancedb.connect(uri= "vector_database")
db

LanceDBConnection(uri='/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_3_lancedb/vector_database')

In [2]:
db.uri

'/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_3_lancedb/vector_database'

## create a table

In [5]:
import json

with open("data/animals_text_embeddings.json", "r") as file: #embeddings is a vector representation of text
    data = json.loads(file.read())

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

In [7]:
table_animals = db.create_table("animals_text", exist_ok= True, data=data)
table_animals

LanceTable(name='animals_text', version=1, _conn=LanceDBConnection(uri='/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_3_lancedb/vector_database'))

In [8]:
table_animals.to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]

In [9]:
more_data = [    
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
    ]

table_animals.add(more_data)

AddResult(version=2)

In [10]:
table_animals.to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

## Create an empty table, then delete it

In [12]:
# 1. add schema to table first - depends on pydantic model

from lancedb.pydantic import LanceModel

LanceModel

lancedb.pydantic.LanceModel

In [13]:
class JokeSchema(LanceModel):
    joke: str
    rating: int

db.create_table(name = "jokes", schema = JokeSchema, exist_ok = True)
db

LanceDBConnection(uri='/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_3_lancedb/vector_database')

In [14]:
# to add data follow established schema

db.table_names()

['animals_text', 'jokes']

In [15]:
# to remove a table, simply drop_table("table_name")

db.drop_table("jokes")

In [16]:
db.table_names()

['animals_text']

## Open existing table

In [17]:
db.open_table("animals_text").head()

pyarrow.Table
text: string
vector: fixed_size_list<item: float>[3]
  child 0, item: float
----
text: [["A small brown dog running.","A cat resting quietly on a sofa.","A large gray elephant drinking water.","A fast cheetah sprinting across the savannah.","A colorful parrot perched on a branch."]]
vector: [[[0.12,0.85,0.33],[0.4,0.91,0.1],[0.88,0.22,0.55],[0.95,0.12,0.72],[0.25,0.66,0.81]]]

## Vector search in LanceDB

In [18]:
table_animals.to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [19]:
# query_vector is search query input

query_vector = [0.5, 0.2, 0.9]

table_animals.search(query_vector).limit(3).to_pandas()

,text,vector,_distance
0,A panda eating bamboo peacefully.,"[0.51, 0.37, 0.82]",0.0354
1,A fast cheetah sprinting across the savannah.,"[0.95, 0.12, 0.72]",0.2413
2,A large gray elephant drinking water.,"[0.88, 0.22, 0.55]",0.2673

## Embedding API

- idea: we want to put in text -> and it will automagically generate vector embeddings
- put in a query and it will automagically generate vector embeddings
- calculate closest distances

In [20]:
from lancedb.pydantic import Vector
from lancedb.embeddings import get_registry

model = get_registry().get("gemini-text").create(name = "gemini-embedding-001")
model

GeminiText(max_retries=7, name='gemini-embedding-001', query_task_type='retrieval_query', source_task_type='retrieval_document')

In [ ]:
# install google-genai 'uv pip install google-genai'

model.generate_embeddings("hello")

[[-0.010894743,
  -0.0028489418,
  0.00893425,
  -0.054541513,
  -0.007433747,
  0.017504206,
  0.014653749,
  0.02498823,
  0.01153613,
  -0.004031619,
  0.0019689437,
  -0.015896015,
  -0.0033653777,
  0.015975969,
  0.09177606,
  -0.02413529,
  0.026621163,
  -0.015998762,
  -0.009193494,
  -0.0032317825,
  0.017314918,
  -0.014104707,
  -0.000599844,
  -0.013850878,
  0.025816025,
  0.027195023,
  0.017755596,
  0.009800108,
  0.022374708,
  0.017374959,
  -0.0027653421,
  0.0067342324,
  0.00040601502,
  0.002778903,
  -0.004352005,
  0.011505135,
  0.022893922,
  -0.010107965,
  -0.0130854435,
  0.022383824,
  0.00030385726,
  -0.007134147,
  0.002239337,
  -0.0012981425,
  7.041567e-05,
  0.011082349,
  -0.005637078,
  -0.025727957,
  0.0059076254,
  0.0042295936,
  0.0017543633,
  0.011937581,
  -0.020759232,
  -0.14057352,
  -0.011109075,
  0.006916541,
  -0.0025381926,
  0.021703891,
  0.0076077846,
  -0.029725924,
  0.010393887,
  0.026465422,
  -0.014564507,
  -0.008960989,
  -0.0278895,
  -0.013143821,
  0.025932917,
  0.018782737,
  -0.007277717,
  0.011100802,
  -0.007302172,
  0.0043212418,
  -0.0045143194,
  0.0043093036,
  -0.01031841,
  0.0069819386,
  0.0071304743,
  0.009563596,
  -0.012977294,
  0.042270605,
  -0.01831609,
  -0.028458375,
  -0.014239028,
  -0.011460251,
  0.0006987148,
  0.0037828432,
  -0.011120268,
  -0.007279127,
  -0.012551258,
  -0.0042546215,
  0.005001188,
  0.011654048,
  0.013459278,
  -0.026933843,
  0.005779235,
  -0.009201566,
  0.005145211,
  0.00490399,
  -0.0035683631,
  0.0068511767,
  0.011755284,
  -0.016186627,
  -0.0013286247,
  0.020250997,
  -0.013469695,
  -0.03154354,
  0.008879823,
  0.006014098,
  -0.012009428,
  -0.003291308,
  -0.00082919054,
  0.009012183,
  0.019133175,
  0.008885957,
  0.0043297824,
  -0.20751265,
  0.008460281,
  -0.017181886,
  -0.006850679,
  0.010617436,
  0.011536425,
  -0.0071962243,
  -0.0010271898,
  -0.006679142,
  -0.0077334,
  -0.018232046,
  0.0034199327,
  -0.0018284925,
  -0.0136822825,
  -0.010364635,
  0.0016082462,
  0.012740099,
  0.020895476,
  -0.028925855,
  0.022254398,
  0.020805182,
  -0.017180556,
  0.004820916,
  -0.000992084,
  0.008635904,
  0.006466806,
  -8.019128e-05,
  0.024454331,
  0.019131053,
  -0.014722803,
  0.0062699057,
  -0.022018414,
  -0.017078115,
  0.0022915488,
  -0.027813174,
  -0.010954208,
  -0.0028691404,
  -0.017401146,
  -0.0014321284,
  0.0045618964,
  -0.053670872,
  -0.0017024488,
  0.011066855,
  0.02336727,
  0.0072743143,
  0.028426943,
  -0.0038358436,
  0.0015755467,
  0.0045387973,
  -0.019761046,
  -0.006387864,
  -0.002886542,
  -0.013430993,
  -0.004872644,
  0.010991768,
  -0.010491402,
  0.004218905,
  0.0005331038,
  0.009074472,
  0.006245508,
  -0.018454002,
  0.013116634,
  0.008405044,
  -0.02607379,
  -0.0024505388,
  0.016906098,
  -0.002226631,
  0.017387604,
  -0.01681773,
  0.0014685016,
  -0.015496952,
  0.0031811313,
  -0.020021455,
  -0.014221316,
  -0.017845353,
  -0.0042030164,
  0.009824213,
  -0.004035922,
  -0.0042756153,
  -0.0013127609,
  0.016973812,
  -0.029653305,
  0.013411013,
  0.012157935,
  -0.019172492,
  0.0033376457,
  -0.023614703,
  0.017573183,
  0.00020139631,
  -0.008571299,
  0.009848198,
  0.00048534037,
  -0.011776163,
  0.011511077,
  0.010927528,
  -0.0093797585,
  -0.0067883017,
  0.009523407,
  -0.0031142263,
  0.014011795,
  0.019919202,
  -0.008621176,
  -0.0027430984,
  -0.009397683,
  0.0003848104,
  0.03421796,
  -0.003793513,
  -0.014944244,
  0.006584726,
  0.0041904184,
  -0.007230043,
  -0.0063115098,
  -0.013932514,
  -0.0030269139,
  0.004997075,
  0.0036656752,
  0.001233697,
  -0.0021096815,
  0.016758723,
  -6.737517e-05,
  0.008696733,
  0.02239819,
  0.013805341,
  0.026058985,
  -0.003100445,
  -0.0017851377,
  -0.014138923,
  -0.0014701751,
  0.010721434,
  0.005706593,
  0.010899184,
  0.006407311,
  -0.0027334483,
  0.010179657,
  0.0024023175,
  0.012393262,
  0.012551334,
  -0.0046072192,
  -0.0073801847,
  0.0097025195,
  0.008116727,
  -0.0027904492,
  -0.016621532,
  -0.01861488,
  -0.017483005,
  0.015929664,
  -0.014126334,
  -0.032372747,
  0.029368991,
  0.02189217,
  0.017452128,
  -0.0012530104,
  0.02122505,
  -0.0021632616,
  0.014150737,
  0.015274288,
  -0.020296065,
  -0.030935528,
  0.0023769727,
  -0.026577948,
  0.0042592897,
  -0.13887966,
  0.010263034,
  0.0051415656,
  -0.018691787,
  -0.00020951159,
  0.0062127463,
  0.0022416469,
  -0.012319782,
  -0.013365082,
  0.018289998,
  0.018429255,
  -0.008051013,
  0.0027776072,
  -0.033673864,
  0.01297796,
  -0.009930479,
  -0.02618195,
  0.013742337,
  0.0029149717,
  -0.004559991,
  -0.0037152688,
  0.016748438,
  -0.011664238,
  -0.0142748,
  -0.0010661888,
  -0.007225828,
  0.0006733771,
  0.03754026,
  0.0060118544,
  0.0026740632,
  -0.011697326,
  0.00085309305,
  0.0076277223,
  0.0033769088,
  0.0050015305,
  -0.040347707,
  0.012523364,
  -0.010876954,
  -0.00020383918,
  -0.026219755,
  -0.0053912066,
  0.0072862734,
  -0.0009839946,
  0.03561125,
  0.024882426,
  0.007036111,
  0.011182695,
  -0.011006118,
  0.004704422,
  -0.0127473315,
  -0.0155108655,
  0.014399099,
  0.025367292,
  0.0075106807,
  0.001461816,
  -0.019970218,
  -0.014539293,
  0.0033555096,
  -0.0029858456,
  0.024256121,
  0.016267713,
  -0.0009932562,
  -0.019014414,
  -0.006814848,
  -0.016553184,
  -0.01407446,
  -0.0026776323,
  0.0063296803,
  0.0046614246,
  -0.03353621,
  0.012626356,
  0.003204428,
  -0.0128875375,
  -0.034066178,
  -0.0060360725,
  -0.011336118,
  0.0061353026,
  -0.008760235,
  -3.5162455e-05,
  0.012674695,
  0.00084275485,
  0.013488029,
  -0.013950393,
  0.0008535957,
  0.022278292,
  -0.018608216,
  -0.0119942855,
  5.8743542e-05,
  0.014840872,
  -0.038597252,
  0.0034389242,
  0.031168697,
  -0.027972996,
  -0.011230608,
  -0.008167183,
  -0.018338742,
  0.0026713344,
  0.0027334637,
  0.014685197,
  0.008320566,
  -0.022378186,
  0.009810983,
  -0.0065944404,
  -0.0005758704,
  0.040350404,
  0.020018652,
  0.022302693,
  0.0026325819,
  -0.016012777,
  0.009574623,
  0.005259565,
  -0.0073801484,
  -0.0053225937,
  -0.0074875774,
  -0.0019113213,
  0.010730916,
  -0.005587542,
  0.00712827,
  -0.00964814,
  0.0053180396,
  0.0040641907,
  0.011626815,
  -0.0051516076,
  0.015835812,
  0.0024248965,
  0.025248919,
  -0.022792745,
  0.007913278,
  -0.00891866,
  -0.016677618,
  -0.0045330413,
  -0.0038743946,
  0.0031943286,
  0.006613112,
  -0.008083605,
  -0.007982685,
  0.0009024215,
  -0.00500832,
  0.026956037,
  -0.013032487,
  -0.017352546,
  -0.005973747,
  0.011347142,
  0.011404638,
  0.009415974,
  0.004752755,
  -0.012002496,
  0.0071365037,
  -0.013812342,
  -0.05433137,
  -0.02534544,
  -0.02100315,
  -0.017804906,
  -0.0034795026,
  0.0016240556,
  -0.0051622894,
  -0.0038793618,
  -0.0040358007,
  -0.01708282,
  -0.011619195,
  -0.0033555364,
  0.004317974,
  0.0018860064,
  0.005663342,
  -0.011342271,
  0.019530986,
  -0.010091361,
  0.0059196865,
  0.007563791,
  -0.027584601,
  0.015872791,
  -0.0006903453,
  -0.01996626,
  -0.021447694,
  0.006593759,
  -0.0026552305,
  0.01924007,
  -0.00906268,
  -0.006652436,
  0.02644693,
  -0.008783241,
  -0.0062536285,
  -0.008612546,
  0.018592129,
  -0.020998623,
  -0.017683083,
  -0.005617247,
  -0.005116706,
  -0.016976533,
  0.004641711,
  -0.0017229614,
  -0.004717439,
  -0.005110637,
  -0.016186178,
  -0.0080648,
  0.010601368,
  -0.0019610843,
  -0.010209899,
  0.012962113,
  0.002432221,
  -0.023826739,
  0.014279232,
  -0.0010300623,
  -0.007656271,
  0.008361088,
  -0.009450652,
  -0.00067937665,
  -0.00833892,
  -0.012859305,
  -0.0016811468,
  -0.019958442,
  -0.009604371,
  -0.0055316235,
  0.013901235,
  0.018198123,
  0.00872702,
  -0.011422659,
  0.015582426,
  -0.016566942,
  0.003398472,
  0.0055592232,
  0.0026529543,
  0.01489227,
  0.0102011785,
  0.02521906,
  -0.0014653106,
  0.002833612,
  -0.0015817354,
  -0.009280549,
  -0.017532155,
  -0.004961705,
  0.004538848,
  -0.0079914145,
  0.0063680937,
  0.010788718,
  -0.0018838561,
  0.006711068,
  -0.0097016515,
  -0.0016873247,
  0.010988933,
  0.00011225041,
  -0.004015343,
  0.0040483344,
  0.0046407534,
  0.009911719,
  0.0092376545,
  -0.008113526,
  -0.013596313,
  0.025859673,
  -0.006249188,
  0.017933562,
  0.0060368623,
  0.013933507,
  0.005776789,
  0.00067529624,
  -0.0022542344,
  -0.0012317266,
  -0.016765447,
  -0.00789014,
  0.0012740255,
  -0.009495306,
  0.02150958,
  -0.01693719,
  0.007351685,
  -0.0014874935,
  0.0037784239,
  -0.006943059,
  0.010233391,
  0.008457034,
  -0.1335525,
  0.019588333,
  -0.01745722,
  -0.009625837,
  0.004361538,
  -0.0008916365,
  -0.011693302,
  -0.0053697242,
  0.001215463,
  0.0021176743,
  -0.008706999,
  0.018969245,
  -0.00017831259,
  0.002893837,
  0.01099905,
  -0.02954883,
  0.008000099,
  0.0092627965,
  -0.0072485083,
  0.0091982,
  0.009892247,
  -0.0027476307,
  -0.0175193,
  0.012970884,
  0.004941728,
  -0.000115676194,
  -0.01358087,
  -0.0042045554,
  0.009479425,
  -0.019315181,
  -0.003116302,
  0.006230198,
  0.016439041,
  0.0023522265,
  0.0036359164,
  0.0067428965,
  -7.153463e-05,
  -0.014844836,
  0.0070500723,
  -0.010239145,
  0.0032883931,
  0.00774399,
  0.007601704,
  -0.015092052,
  -0.0058240467,
  0.013821893,
  0.029222557,
  -0.02847315,
  0.00011688512,
  0.011248517,
  -0.019995796,
  0.008697254,
  0.0052282494,
  -0.0010132528,
  0.005978291,
  -0.0190166,
  0.016426226,
  0.0003406773,
  -0.014018681,
  0.0055770385,
  0.0007654627,
  0.015489088,
  0.0011887199,
  0.012866499,
  -0.011217138,
  -0.0039836685,
  -0.0034189897,
  -0.0098933475,
  0.0032236786,
  0.014359961,
  0.0062892004,
  0.007601715,
  -0.02601815,
  0.04957646,
  0.034250688,
  0.009490558,
  0.023824159,
  -0.016867442,
  0.027438916,
  0.017702587,
  0.005099144,
  0.0062574726,
  -0.07889941,
  0.006876871,
  0.0070047597,
  0.00030894615,
  0.014244326,
  0.03504839,
  0.013071293,
  -0.00051515497,
  0.0033965742,
  0.00654745,
  0.0010265876,
  0.0028040402,
  -0.0031594709,
  0.010432087,
  0.012584873,
  0.018287625,
  -0.012226879,
  0.002215471,
  -0.012944239,
  0.012420691,
  0.005425689,
  -0.009403913,
  0.017666217,
  -0.01340299,
  -0.003034435,
  0.022995574,
  -0.008066396,
  0.0047288896,
  0.017556831,
  -0.001521921,
  -0.015994916,
  -0.14119162,
  0.003412359,
  -0.012451539,
  0.0019640168,
  0.0037869497,
  0.011215636,
  0.00733804,
  0.009210608,
  -0.0011827414,
  -0.0041616196,
  0.005950439,
  -0.009566941,
  -0.005870629,
  -0.00609883,
  -0.0053024264,
  0.18468662,
  -0.004073989,
  -0.013069701,
  -0.008830245,
  -0.025546879,
  -0.0034881923,
  -0.0002587228,
  -0.00457912,
  0.012891762,
  0.009106349,
  -0.0046674917,
  -0.009712552,
  -0.005945681,
  0.01070655,
  0.0038376818,
  0.0027948897,
  0.0069105937,
  -0.009203186,
  -0.0001259372,
  0.011130588,
  -0.016051678,
  -0.0018381273,
  0.0037273248,
  0.0065940702,
  0.020343853,
  0.01717756,
  0.0034270647,
  -0.0018863382,
  0.015417528,
  -0.02615422,
  -0.008180734,
  0.00043717344,
  -0.015739663,
  0.021392,
  -0.010964484,
  -0.019155862,
  -0.08583935,
  0.0011632827,
  0.015324002,
  0.016038442,
  -0.015976958,
  0.009727368,
  0.016382502,
  -0.006216813,
  -0.019160086,
  -0.0061438894,
  -0.022571426,
  -0.018272186,
  -0.0017562202,
  -0.018620348,
  -0.0006531316,
  0.014018077,
  0.0055846027,
  -0.027664563,
  -0.0048044464,
  -0.012357348,
  -0.0035173811,
  -0.01167685,
  0.0006767786,
  -0.041234713,
  -0.03648998,
  -0.0030282335,
  -0.005276776,
  -0.005789101,
  -0.010476702,
  -0.005335548,
  -0.0018733044,
  0.0053455974,
  -0.014061311,
  -0.0036823086,
  0.0021317615,
  -0.0128209945,
  0.025630306,
  0.012682009,
  0.02106133,
  0.020677952,
  0.009765132,
  0.026000952,
  -0.011005044,
  -0.009051811,
  -0.00073926616,
  -0.0072622616,
  0.00870079,
  0.010477917,
  0.005288411,
  0.006683381,
  -0.0067763273,
  -0.0017099039,
  -0.0196155,
  -0.0020095624,
  0.0056288834,
  0.015693115,
  0.014588649,
  -0.0065653636,
  0.021015288,
  -0.005052822,
  -0.007622224,
  0.001229676,
  0.005412601,
  0.015202764,
  -0.018245844,
  0.008337046,
  -0.0030921905,
  -0.0020797285,
  -0.007879484,
  0.0016834674,
  -0.0012817705,
  -0.007696198,
  0.0010896018,
  -0.0062553477,
  -0.0057589724,
  -0.009580964,
  0.0013608303,
  -0.00015675552,
  0.0013554611,
  -0.011224856,
  -0.010187546,
  -0.0066924617,
  0.0040886197,
  0.018141737,
  -8.805156e-05,
  0.0029274349,
  0.00048065113,
  -0.0023166894,
  -0.0052617723,
  -0.00042049825,
  0.0049091126,
  -0.005945528,
  -0.015227551,
  0.011223707,
  0.017569058,
  0.010939507,
  0.017362889,
  -0.0101809,
  -0.0009858726,
  0.0029497165,
  -0.009745321,
  -0.0029590663,
  -0.0021572171,
  0.005613095,
  0.003103779,
  0.013436948,
  0.027176803,
  -0.0011015356,
  0.0035356923,
  0.017066387,
  0.005246163,
  0.005161678,
  0.01826232,
  -0.0037229948,
  0.0068038404,
  -0.002258341,
  -0.0015850133,
  0.0050923806,
  0.007635873,
  0.0120243095,
  -0.004750751,
  -0.011677145,
  -0.0037846596,
  -0.009036709,
  0.004903971,
  -0.0023473436,
  -0.00551732,
  -0.0052086753,
  -0.014484998,
  0.0024907466,
  0.021320669,
  -0.0011875757,
  0.009095205,
  -0.008935948,
  0.0045586373,
  -0.010647083,
  -0.0018573466,
  -0.004576072,
  -0.000541635,
  0.0026298019,
  -0.028296748,
  -0.002394597,
  0.0027224168,
  0.0039558117,
  0.0003192451,
  -0.00073932495,
  0.0075309547,
  -0.0030602,
  -0.004974659,
  0.014144129,
  -0.00051911763,
  0.0061759707,
  0.00936958,
  -0.0057884874,
  -0.0038183674,
  -0.015828954,
  0.0037143615,
  -0.013070024,
  -0.0027730989,
  -0.0015073412,
  0.0032869366,
  -0.0070782527,
  -0.008525548,
  -0.003751141,
  -0.009097281,
  -0.009292836,
  0.00019279498,
  -0.0030675977,
  -0.0043112575,
  0.011569544,
  -0.010578738,
  0.002301014,
  -0.00787646,
  0.012578381,
  0.0027191965,
  0.013522748,
  0.00054621807,
  0.014598556,
  0.0094867535,
  -0.008874677,
  -0.009519359,
  0.0017544468,
  0.002554341,
  -0.0024183982,
  0.0044003045,
  -0.0055459966,
  0.010862059,
  0.004814714,
  -0.005599954,
  -0.007244069,
  0.008407414,
  -0.0054680756,
  -0.012945354,
  -0.0018762838,
  -0.012620795,
  0.00825302,
  0.0022807498,
  -0.034032125,
  0.018370511,
  -0.022100488,
  0.0023492975,
  -0.000974027,
  0.007242198,
  -0.005170915,
  -0.014231295,
  -0.001267311,
  0.018425856,
  -0.013911271,
  -0.006646409,
  0.00862705,
  -0.004373564,
  -0.0009493634,
  0.0062640626,
  -0.0143030565,
  0.001244881,
  0.0066192104,
  -0.00243113,
  -0.005826174,
  0.01294599,
  -0.0048221885,
  -0.012960722,
  0.0071106744,
  0.005958261,
  -0.0017260539,
  0.017922623,
  -0.0022078876,
  0.00017349533,
  0.0027678076,
  0.0013835673,
  -0.0030217525,
  -0.00994736,
  0.005265336,
  -0.0016567559,
  0.013058739,
  0.008182066,
  0.009688924,
  -0.0016845965,
  -0.009168589,
  -0.008871877,
  0.0028425092,
  -0.0046446077,
  0.0075319177,
  0.023532575,
  -0.009171777,
  -0.014710161,
  -0.009327622,
  0.0038214368,
  -0.005441889,
  -0.0030180945,
  -0.014710688,
  -0.0087116975,
  -0.011497554,
  -0.014553731,
  0.006682543,
  -0.0047386517,
  0.01581985,
  0.000371841,
  -0.0041484195,
  -0.0055052573,
  0.10962548,
  0.006917467,
  -0.002005446,
  -0.0030358692,
  0.008584938,
  -0.004721721,
  0.0106049115,
  -0.014574787,
  -0.009912092,
  -0.018153552,
  0.00014084688,
  -0.019046025,
  0.0066852663,
  0.0063411347,
  -0.012405708,
  0.0052172304,
  0.0027824389,
  -0.0005344631,
  -0.00972473,
  -0.010901522,
  -0.004586749,
  -0.0059901844,
  0.008976435,
  -0.019208388,
  0.005264209,
  0.0011681984,
  -0.0019370801,
  -0.0056056785,
  -0.015082174,
  -0.008606397,
  0.0031709373,
  0.007422166,
  ...],
 [-0.00069592486,
  0.011804536,
  0.0036298153,
  -0.055664122,
  -0.0133999465,
  0.0049628294,
  0.006362748,
  0.0010908127,
  -0.0013382478,
  0.0047416994,
  -0.0010297787,
  -0.028999265,
  -0.0019098793,
  0.0124251135,
  0.096216865,
  -0.010009603,
  0.014532839,
  -0.0066989944,
  -0.011754898,
  -0.007756512,
  0.018570239,
  -0.011319722,
  0.014589949,
  0.006638819,
  -0.012775049,
  0.0050727366,
  0.016235683,
  0.002290508,
  0.028284004,
  0.0010383269,
  -0.002799452,
  -0.011979931,
  -0.006750065,
  0.008716034,
  0.0063068857,
  -0.014902086,
  0.012810869,
  0.008352956,
  -0.006121823,
  0.0050440696,
  -0.014506352,
  -0.012816858,
  0.013311125,
  0.021954145,
  -0.008216812,
  0.012398979,
  -0.016994705,
  -0.008323599,
  -0.010815867,
  -0.010351272,
  0.0048546945,
  -0.005341541,
  -0.030668812,
  -0.14793009,
  -0.00969634,
  -0.010808164,
  -0.024054613,
  0.014268918,
  0.018928988,
  0.007833439,
  -0.024318011,
  -0.0016322064,
  -0.004122924,
  -0.026841078,
  0.0018331305,
  0.015796399,
  0.0059692455,
  0.011301491,
  -0.026108593,
  -0.005342515,
  0.014108106,
  0.011787519,
  -0.004556565,
  -0.004548293,
  0.009177684,
  -0.010700724,
  0.023796031,
  -0.010516861,
  -0.03192521,
  0.02767601,
  -0.0056829033,
  -0.030103449,
  -0.017790306,
  -0.006252492,
  -0.024153918,
  0.0057947095,
  -0.019432262,
  0.017596692,
  -0.005119284,
  -0.0087571,
  -0.0016836144,
  -0.018108236,
  0.0008314769,
  -0.013975006,
  -0.0040830527,
  0.0047188895,
  -0.019339208,
  0.019561766,
  -0.006438568,
  0.007676775,
  -0.014691336,
  -0.022022158,
  0.011586375,
  0.008313815,
  0.013620216,
  -0.021162383,
  -0.008070932,
  0.0023142013,
  -0.0010005373,
  -0.0054607796,
  0.0030773534,
  -0.011741526,
  0.02422,
  0.028519481,
  -0.0010472583,
  -0.20243251,
  0.02361464,
  0.0034730928,
  -0.01309393,
  -0.008880547,
  0.010129041,
  -0.023050865,
  -0.011874431,
  0.0049437173,
  0.009243175,
  -0.01609477,
  -0.0040340032,
  -0.012101172,
  0.0047672587,
  0.01511025,
  0.02129638,
  -0.0147446,
  0.004574038,
  0.0122514935,
  -0.017180312,
  0.030775493,
  -0.033958077,
  -0.006311041,
  0.0029402575,
  0.008393636,
  -0.024961706,
  0.009701255,
  0.016754365,
  0.0143302735,
  -0.0016929398,
  0.017486557,
  -0.027845211,
  -0.014918252,
  0.0067811017,
  -0.04547204,
  -0.016406408,
  0.014737786,
  0.0052920515,
  0.003352938,
  0.014216026,
  -0.06388969,
  0.014882875,
  -0.0057622693,
  0.009354525,
  -0.022686457,
  -0.018460957,
  0.0050698114,
  0.007110113,
  0.003427815,
  -0.009473555,
  -0.008075899,
  0.014876631,
  0.02508739,
  0.0030919786,
  -0.0073827803,
  -0.04697334,
  0.007711116,
  -0.004476681,
  0.0041867965,
  -0.00058433315,
  -0.0038938532,
  -0.0040924633,
  0.0048927264,
  0.015022283,
  -0.005107087,
  0.023831021,
  -0.022395417,
  -0.010497312,
  -0.0034503262,
  0.013555729,
  -0.0106589375,
  -0.020102024,
  -0.0014670442,
  -0.005037174,
  -0.008234719,
  -0.046174314,
  -0.0066460925,
  0.0074645607,
  -0.024142252,
  0.013786668,
  0.0063020047,
  -0.009276369,
  0.026729716,
  -0.035294615,
  -0.0009208986,
  0.0055054333,
  -0.011627131,
  0.005322152,
  0.013065367,
  -0.002905855,
  -0.004120169,
  -0.0030785422,
  -0.03274302,
  0.01870561,
  0.022354197,
  -0.00043389125,
  -9.168402e-06,
  0.013617735,
  -0.0053106784,
  0.032640457,
  -0.01739914,
  -0.019124204,
  -0.024936546,
  -0.003934506,
  -0.009199414,
  0.0103618,
  -0.0019430459,
  -0.0063545373,
  -0.006542634,
  -0.017848693,
  -0.0040007094,
  0.0070481026,
  -0.01545447,
  -0.016699411,
  0.0003690338,
  -0.0011833707,
  -0.0059380345,
  -0.010515431,
  0.000247048,
  0.011655879,
  -0.0022047674,
  -0.017786017,
  -0.037436083,
  0.008726785,
  0.00299089,
  -0.0012279112,
  -0.0045731165,
  0.00798089,
  0.002311345,
  0.011198521,
  -0.015981698,
  0.0067136805,
  0.0044151074,
  0.016546937,
  -0.0028599477,
  0.015167912,
  0.0055336896,
  -0.0062638023,
  0.0055215727,
  -0.0013576434,
  0.0028155649,
  0.0121647725,
  -0.009856035,
  -0.0072684623,
  0.022561079,
  0.014242692,
  -0.029094351,
  -0.012952185,
  -0.011786703,
  -0.00547415,
  -0.0016427606,

In [25]:
import numpy as np
hello_embedding = np.array(model.generate_embeddings("hello"))
hello_embedding.shape

(5, 3072)

In [ ]:
model.ndims() # gives a different dimension than the actual? so hard code '3072' which is actual shape

768

In [27]:
class JokeModel(LanceModel):
    joke: str = model.SourceField() # marks a text as input to embedding function
    vector: Vector(3072) = model.VectorField() # a vector is the destination of a computed embedding

table_jokes = db.create_table("jokes", schema=JokeModel, exist_ok=True)
table_jokes

LanceTable(name='jokes', version=1, _conn=LanceDBConnection(uri='/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_3_lancedb/vector_database'))